addSbtPlugin("com.geirsson"     %  "sbt-scalafmt"           % "1.4.0")
addSbtPlugin("com.timushev.sbt" %  "sbt-updates"            % "0.3.1")
addSbtPlugin("io.spray"         %  "sbt-revolver"           % "0.9.1")
addSbtPlugin("org.scalastyle"   %% "scalastyle-sbt-plugin"  % "1.0.0")
addSbtPlugin("org.scoverage"    %  "sbt-coveralls"          % "1.2.7")
addSbtPlugin("org.scoverage"    %  "sbt-scoverage"          % "1.5.1")
addSbtPlugin("org.wartremover"  %  "sbt-wartremover"        % "2.4.1")